# Generated by Django 3.1.4 on 2020-12-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliend_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
            ],
        ),
    ]
