# Generated by Django 3.1.4 on 2020-12-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='cliend_id',
            new_name='client_id',
        ),
    ]
